spring:
  datasource:
    url: jdbc:mysql://182.92.209.153:3306/jinguan
    driver-class-name: com.mysql.jdbc.Driver
    username: jinguan
    password: jinguan888
  rabbitmq:
    host: 5672
    username: flysun
    password: 19951226fly
    virtual-host: jinguanyun
  redis:
    host: 182.92.209.153
    port: 6379

socket:
  # 监听端口 8099
  port: 8099
  #ip地址
#  host: 127.0.0.1
